name: Development CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pre_build:
    name: Run basic checks and formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - run: yarn --frozen-lockfile

      - run: yarn prettier --check .

      - run: yarn prettier --write .

  release:
    name: Push to release branch if tag is present
    runs-on: ubuntu-latest
    needs: pre_build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - run: |
          git push origin main:release
